// Auto-generated by scripts/package.ts at build time. Committed as an
// empty stub so dev typecheck passes without a prior build; the real
// base64 payloads land here during `mise run package` and are
// restored to the stub at build-end so git diffs stay clean.

export const PARSER_WORKER_JS_BASE64 = "";
export const TREE_SITTER_WASM_FILENAME = "";
export const TREE_SITTER_WASM_BASE64 = "";
