#!/usr/bin/env bun
/**
 * Package the ordin CLI into a single-file executable via `Bun.build`.
 *
 * Uses the programmatic API rather than `bun build --compile` because
 * the CLI form has no `--plugin` flag, and `@opentui/solid` JSX needs
 * the babel-preset-solid transform at build time (the `bunfig.toml`
 * preload only fires at runtime, not under AOT compile).
 *
 * Single-file distribution: the tree-sitter Worker (parser.worker.js)
 * and its wasm sibling are bundled separately, base64-encoded, and
 * written into `src/cli/embedded-assets.generated.ts` before the main
 * binary build. The compiled binary decodes them to a cache dir under
 * `~/.cache/ordin/lib-<hash>/` at first run — Bun's --compile VFS
 * can't host a Worker entry point, but a cache dir on real disk can.
 *
 * The generated file is committed as an empty stub; this script
 * overwrites with real base64 just before the main build and restores
 * the stub at the end so git diffs stay clean. Dev typecheck reads
 * the stub (empty strings) and `setupCompiledRuntime` early-returns
 * when the embedded payload is empty.
 *
 * Target defaults to the host platform; override via `--target=<spec>`
 * e.g. `bun-darwin-arm64`, `bun-linux-x64`.
 */
import { mkdir, readdir, readFile, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import createSolidTransformPlugin from "@opentui/solid/bun-plugin";

interface BuildOpts {
  readonly target: string;
  readonly outfile: string;
}

function parseArgs(argv: readonly string[]): BuildOpts {
  let target = `bun-${process.platform === "darwin" ? "darwin" : "linux"}-${
    process.arch === "arm64" ? "arm64" : "x64"
  }`;
  let outfile = "dist/ordin";
  for (const arg of argv.slice(2)) {
    if (arg.startsWith("--target=")) target = arg.slice("--target=".length);
    else if (arg.startsWith("--outfile=")) outfile = arg.slice("--outfile=".length);
    else throw new Error(`Unknown argument: ${arg}`);
  }
  return { target, outfile };
}

const opts = parseArgs(process.argv);
const distDir = dirname(opts.outfile);
await mkdir(distDir, { recursive: true });
const repoRoot = join(import.meta.dir, "..");

// ----- Step 1: build the tree-sitter worker bundle ------------------------
// @opentui/core spawns parser.worker.js as a Web Worker. Bundling it
// standalone inlines web-tree-sitter + its node deps so the worker is
// self-contained when we extract it to a cache dir at runtime.
const workerStart = Date.now();
const workerEntry = join(repoRoot, "node_modules", "@opentui", "core", "parser.worker.js");
const workerResult = await Bun.build({
  entrypoints: [workerEntry],
  target: "bun",
  outdir: distDir,
  naming: "parser.worker.js",
});
if (!workerResult.success) {
  for (const log of workerResult.logs) console.error(log);
  process.exit(1);
}

// Bun emits the wasm path as `"./tree-sitter-<hash>.wasm"` — relative,
// resolved against process.cwd() by emscripten. Patch to resolve
// against `import.meta.url` (the worker file's own URL), so the wasm
// is found via the cache dir at runtime regardless of caller cwd.
const workerPath = join(distDir, "parser.worker.js");
const originalWorker = await readFile(workerPath, "utf8");
const patchedWorker = originalWorker.replace(
  /module2\.exports\s*=\s*"(\.\/tree-sitter-[a-z0-9]+\.wasm)";/,
  'module2.exports = new URL("$1", import.meta.url).pathname;',
);
if (patchedWorker === originalWorker) {
  console.error(
    "✗ failed to patch tree-sitter wasm path in parser.worker.js — Bun bundler output changed shape?",
  );
  process.exit(1);
}
console.log(`✓ ${workerPath} (${Date.now() - workerStart}ms, wasm path patched)`);

// Find the emitted wasm sibling (Bun hashes the filename).
const wasmName = (await readdir(distDir)).find(
  (f) => f.startsWith("tree-sitter-") && f.endsWith(".wasm"),
);
if (!wasmName) {
  console.error("✗ expected tree-sitter-*.wasm sibling next to parser.worker.js");
  process.exit(1);
}
const wasmBytes = await readFile(join(distDir, wasmName));

// ----- Step 2: write the embedded-assets generated file -------------------
// The main binary build imports this module; it must exist with real
// content before the main build runs.
const generatedPath = join(repoRoot, "src", "cli", "embedded-assets.generated.ts");
const workerBase64 = Buffer.from(patchedWorker, "utf8").toString("base64");
const wasmBase64 = wasmBytes.toString("base64");
const generated = `// Auto-generated by scripts/package.ts. Do not edit.
// Gitignored; committed stub keeps dev typecheck green between builds.

export const PARSER_WORKER_JS_BASE64 = ${JSON.stringify(workerBase64)};
export const TREE_SITTER_WASM_FILENAME = ${JSON.stringify(wasmName)};
export const TREE_SITTER_WASM_BASE64 = ${JSON.stringify(wasmBase64)};
`;
await Bun.write(generatedPath, generated);
console.log(
  `✓ ${generatedPath} (worker ${(patchedWorker.length / 1024).toFixed(0)}KB + wasm ${(wasmBytes.length / 1024).toFixed(0)}KB)`,
);

// ----- Step 3: build the main binary --------------------------------------
const start = Date.now();
const result = await Bun.build({
  entrypoints: [join(repoRoot, "src", "cli", "index.ts")],
  target: "bun",
  plugins: [createSolidTransformPlugin],
  // Compile-time marker the runtime checks to distinguish installed
  // binary from dev runs.
  define: {
    __ORDIN_COMPILED__: "true",
  },
  compile: {
    target: opts.target as Bun.Build.CompileTarget,
    outfile: opts.outfile,
  },
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
console.log(`✓ ${opts.outfile} (${opts.target}, ${Date.now() - start}ms)`);

// ----- Step 4: clean up build intermediates -------------------------------
// The worker + wasm are now embedded in the binary; their on-disk
// copies in dist/ are no longer load-bearing for distribution.
await rm(workerPath, { force: true });
await rm(join(distDir, wasmName), { force: true });
await rm(join(distDir, "parser.worker.js.map"), { force: true });

// Restore the embedded-assets stub so dev typecheck stays consistent
// and git doesn't see noisy diffs for the generated payload.
const STUB = `// Auto-generated by scripts/package.ts at build time. Committed as an
// empty stub so dev typecheck passes without a prior build; the real
// base64 payloads land here during \`mise run package\`. Gitignored so
// the committed stub stays stable across builds.

export const PARSER_WORKER_JS_BASE64 = "";
export const TREE_SITTER_WASM_FILENAME = "";
export const TREE_SITTER_WASM_BASE64 = "";
`;
await Bun.write(generatedPath, STUB);
